"""empty message

Revision ID: 03d55e4cb3ca
Revises: e7185ef4f16a
Create Date: 2023-11-09 01:13:36.093525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d55e4cb3ca'
down_revision = 'e7185ef4f16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
