"""empty message

Revision ID: 7d07c38d8ba5
Revises: 41d94ba76da3
Create Date: 2023-11-14 11:05:54.237985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d07c38d8ba5'
down_revision = '41d94ba76da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_added', sa.DateTime(), nullable=True))
        batch_op.alter_column('cover',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('time_added')

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('cover',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.drop_column('time_added')

    # ### end Alembic commands ###
