"""empty message

Revision ID: c7e1db841163
Revises: 3454daa3aafc
Create Date: 2023-11-07 23:53:28.676695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e1db841163'
down_revision = '3454daa3aafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Song_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_added', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cover', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('play_count', sa.Integer(), nullable=True))
        batch_op.alter_column('lyrics',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('upload_time')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(), nullable=True))
        batch_op.drop_column('dp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dp', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('cover')

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_time', sa.TIME(), nullable=True))
        batch_op.alter_column('lyrics',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.drop_column('play_count')
        batch_op.drop_column('cover')
        batch_op.drop_column('time_added')

    op.drop_table('Song_ratings')
    # ### end Alembic commands ###
