"""empty message

Revision ID: e7185ef4f16a
Revises: c7e1db841163
Create Date: 2023-11-08 09:58:29.206986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7185ef4f16a'
down_revision = 'c7e1db841163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('genre')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
